using Codando.Gerador.Domain.Base;
using System.Text;

namespace Codando.Gerador.Domain.VisualBasic.ProjetoWeb
{
    class ArquivoVbProj : Base.Arquivo
    {

        private Projeto _projeto;

        public ArquivoVbProj(Projeto projeto)
        {
            this.UsarArquivoSeparadoParaRegerar = false;
            this._projeto = projeto;
            this.Nome = this._projeto.NomeProjeto;
            this.Extensao = this._projeto.ExtensaoProjeto;
        }

        public override string GetConteudoGeradoApenasUmaVez()
        {
            return "";
        }

        public override string GetConteudoRegerado()
        {
            var _str = new StringBuilder();
            _str.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            _str.AppendLine("<Project ToolsVersion=\"12.0\" DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">");
            _str.AppendLine("  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.Default.props\" Condition=\"Exists('$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.Default.props')\" />");
            _str.AppendLine("  <Import Project=\"..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props\" Condition=\"Exists('..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')\" />");
            _str.AppendLine("  <Import Project=\"$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props\" Condition=\"Exists('$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props')\" />");
            _str.AppendLine("  <PropertyGroup>");
            _str.AppendLine("    <Configuration Condition=\" '$(Configuration)' == '' \">Debug</Configuration>");
            _str.AppendLine("    <Platform Condition=\" '$(Platform)' == '' \">AnyCPU</Platform>");
            _str.AppendLine("    <ProductVersion>");
            _str.AppendLine("    </ProductVersion>");
            _str.AppendLine("    <SchemaVersion>");
            _str.AppendLine("    </SchemaVersion>");
            _str.AppendLine("    <ProjectGuid>{" + this._projeto.GuIdProjeto + "}</ProjectGuid>");
            _str.AppendLine("    <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{F184B08F-C81C-45F6-A57F-5ABD9991F28F}</ProjectTypeGuids>");
            _str.AppendLine("    <OutputType>Library</OutputType>");
            _str.AppendLine("    <RootNamespace>" + this._projeto.NomeProjeto + "</RootNamespace>");
            _str.AppendLine("    <AssemblyName>" + this._projeto.NomeProjeto + "</AssemblyName>");
            _str.AppendLine("    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>");
            _str.AppendLine("    <MyType>Custom</MyType>");
            _str.AppendLine("    <UseIISExpress>true</UseIISExpress>");
            _str.AppendLine("    <Use64BitIISExpress />");
            _str.AppendLine("    <IISExpressSSLPort />");
            _str.AppendLine("    <IISExpressAnonymousAuthentication />");
            _str.AppendLine("    <IISExpressWindowsAuthentication />");
            _str.AppendLine("    <IISExpressUseClassicPipelineMode />");
            _str.AppendLine("    <UseGlobalApplicationHostFile />");
            _str.AppendLine("    <SccProjectName>SAK</SccProjectName>");
            _str.AppendLine("    <SccLocalPath>SAK</SccLocalPath>");
            _str.AppendLine("    <SccAuxPath>SAK</SccAuxPath>");
            _str.AppendLine("    <SccProvider>SAK</SccProvider>");
            _str.AppendLine("    <NuGetPackageImportStamp>");
            _str.AppendLine("    </NuGetPackageImportStamp>");
            _str.AppendLine("    <TypeScriptToolsVersion>3.5</TypeScriptToolsVersion>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \">");
            _str.AppendLine("    <DebugSymbols>true</DebugSymbols>");
            _str.AppendLine("    <DebugType>full</DebugType>");
            _str.AppendLine("    <DefineDebug>true</DefineDebug>");
            _str.AppendLine("    <DefineTrace>true</DefineTrace>");
            _str.AppendLine("    <OutputPath>bin\\</OutputPath>");
            _str.AppendLine("    <DocumentationFile>WebForms_Basic.xml</DocumentationFile>");
            _str.AppendLine("    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \">");
            _str.AppendLine("    <DebugSymbols>true</DebugSymbols>");
            _str.AppendLine("    <DebugType>pdbonly</DebugType>");
            _str.AppendLine("    <DefineDebug>false</DefineDebug>");
            _str.AppendLine("    <DefineTrace>true</DefineTrace>");
            _str.AppendLine("    <Optimize>true</Optimize>");
            _str.AppendLine("    <OutputPath>bin\\</OutputPath>");
            _str.AppendLine("    <DocumentationFile>WebForms_Basic.xml</DocumentationFile>");
            _str.AppendLine("    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Reference Include=\"AjaxControlToolkit, Version=4.5.7.1213, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e, processorArchitecture=MSIL\">");
            _str.AppendLine("      <SpecificVersion>False</SpecificVersion>");
            _str.AppendLine("      <HintPath>lib\\AjaxControlToolkit.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"AjaxMin, Version=4.97.4951.28478, Culture=neutral, PublicKeyToken=21ef50ce11b5d80f, processorArchitecture=MSIL\">");
            _str.AppendLine("      <SpecificVersion>False</SpecificVersion>");
            _str.AppendLine("      <HintPath>lib\\AjaxMin.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.CSharp\" />");
            _str.AppendLine("    <Reference Include=\"Microsoft.IdentityModel.JsonWebTokens, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.IdentityModel.JsonWebTokens.5.6.0\\lib\\net461\\Microsoft.IdentityModel.JsonWebTokens.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.IdentityModel.Logging, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.IdentityModel.Logging.5.6.0\\lib\\net461\\Microsoft.IdentityModel.Logging.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.IdentityModel.Tokens, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.IdentityModel.Tokens.5.6.0\\lib\\net461\\Microsoft.IdentityModel.Tokens.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.ReportViewer.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.ReportingServices.ReportViewerControl.WebForms.150.1358.0\\lib\\net40\\Microsoft.ReportViewer.Common.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.ReportViewer.Design, Version=15.3.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.ReportingServices.ReportViewerControl.WebForms.150.1358.0\\lib\\net40\\Microsoft.ReportViewer.Design.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.ReportViewer.WebDesign, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.ReportingServices.ReportViewerControl.WebForms.150.1358.0\\lib\\net40\\Microsoft.ReportViewer.WebDesign.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.ReportViewer.WebForms, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.ReportingServices.ReportViewerControl.WebForms.150.1358.0\\lib\\net40\\Microsoft.ReportViewer.WebForms.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.SqlServer.Types, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.SqlServer.Types.14.0.1016.290\\lib\\net40\\Microsoft.SqlServer.Types.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Newtonsoft.Json.12.0.2\\lib\\net45\\Newtonsoft.Json.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System\" />");
            _str.AppendLine("    <Reference Include=\"System.Data\" />");
            _str.AppendLine("    <Reference Include=\"System.Drawing\" />");
            _str.AppendLine("    <Reference Include=\"System.Core\" />");
            _str.AppendLine("    <Reference Include=\"System.ComponentModel.DataAnnotations\" />");
            _str.AppendLine("    <Reference Include=\"System.Data.DataSetExtensions\" />");
            _str.AppendLine("    <Reference Include=\"System.IdentityModel.Tokens.Jwt, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\System.IdentityModel.Tokens.Jwt.5.6.0\\lib\\net461\\System.IdentityModel.Tokens.Jwt.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System.Net.Http\" />");
            _str.AppendLine("    <Reference Include=\"System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebApi.Client.5.2.7\\lib\\net45\\System.Net.Http.Formatting.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System.Runtime.Serialization\" />");
            _str.AppendLine("    <Reference Include=\"System.Web.Cors, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.Cors.5.2.7\\lib\\net45\\System.Web.Cors.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System.Web.Extensions\" />");
            _str.AppendLine("    <Reference Include=\"System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebApi.Core.5.2.7\\lib\\net45\\System.Web.Http.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System.Web.Http.Cors, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebApi.Cors.5.2.7\\lib\\net45\\System.Web.Http.Cors.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System.Web.Http.WebHost, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.WebApi.WebHost.5.2.7\\lib\\net45\\System.Web.Http.WebHost.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System.Xml.Linq\" />");
            _str.AppendLine("    <Reference Include=\"System.Web\" />");
            _str.AppendLine("    <Reference Include=\"System.Xml\" />");
            _str.AppendLine("    <Reference Include=\"System.Configuration\" />");
            _str.AppendLine("    <Reference Include=\"System.Web.Services\" />");
            _str.AppendLine("    <Reference Include=\"System.EnterpriseServices\" />");
            _str.AppendLine("    <Reference Include=\"System.Web.DynamicData\" />");
            _str.AppendLine("    <Reference Include=\"System.Web.Entity\" />");
            _str.AppendLine("    <Reference Include=\"System.Web.ApplicationServices\" />");
            _str.AppendLine("    <Reference Include=\"Microsoft.Web.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">");
            _str.AppendLine("      <Private>True</Private>");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.Web.Infrastructure.1.0.0.0\\lib\\net40\\Microsoft.Web.Infrastructure.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"AspNet.ScriptManager.bootstrap\">");
            _str.AppendLine("      <HintPath>..\\packages\\AspNet.ScriptManager.bootstrap.3.4.1\\lib\\net45\\AspNet.ScriptManager.bootstrap.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"AspNet.ScriptManager.jQuery\">");
            _str.AppendLine("      <HintPath>..\\packages\\AspNet.ScriptManager.jQuery.3.3.1\\lib\\net45\\AspNet.ScriptManager.jQuery.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"System.Web.Optimization, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.Web.Optimization.1.1.3\\lib\\net40\\System.Web.Optimization.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"WebGrease\">");
            _str.AppendLine("      <Private>True</Private>");
            _str.AppendLine("      <HintPath>..\\packages\\WebGrease.1.6.0\\lib\\WebGrease.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Antlr3.Runtime\">");
            _str.AppendLine("      <Private>True</Private>");
            _str.AppendLine("      <HintPath>..\\packages\\Antlr.3.5.0.2\\lib\\Antlr3.Runtime.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.AspNet.Web.Optimization.WebForms\">");
            _str.AppendLine("      <Private>True</Private>");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.Web.Optimization.WebForms.1.1.3\\lib\\net45\\Microsoft.AspNet.Web.Optimization.WebForms.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("    <Reference Include=\"Microsoft.AspNet.FriendlyUrls\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.AspNet.FriendlyUrls.Core.1.0.2\\lib\\net45\\Microsoft.AspNet.FriendlyUrls.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Reference Include=\"Microsoft.CodeDom.Providers.DotNetCompilerPlatform\">");
            _str.AppendLine("      <HintPath>..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\\lib\\net45\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll</HintPath>");
            _str.AppendLine("    </Reference>");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Import Include=\"Microsoft.VisualBasic\" />");
            _str.AppendLine("    <Import Include=\"System\" />");
            _str.AppendLine("    <Import Include=\"System.Collections\" />");
            _str.AppendLine("    <Import Include=\"System.Collections.Generic\" />");
            _str.AppendLine("    <Import Include=\"System.Data\" />");
            _str.AppendLine("    <Import Include=\"System.Linq\" />");
            _str.AppendLine("    <Import Include=\"System.Xml.Linq\" />");
            _str.AppendLine("    <Import Include=\"System.Diagnostics\" />");
            _str.AppendLine("    <Import Include=\"System.Collections.Specialized\" />");
            _str.AppendLine("    <Import Include=\"System.Configuration\" />");
            _str.AppendLine("    <Import Include=\"System.Text\" />");
            _str.AppendLine("    <Import Include=\"System.Text.RegularExpressions\" />");
            _str.AppendLine("    <Import Include=\"System.Web\" />");
            _str.AppendLine("    <Import Include=\"System.Web.Caching\" />");
            _str.AppendLine("    <Import Include=\"System.Web.Routing\" />");
            _str.AppendLine("    <Import Include=\"System.Web.SessionState\" />");
            _str.AppendLine("    <Import Include=\"System.Web.Security\" />");
            _str.AppendLine("    <Import Include=\"System.Web.Profile\" />");
            _str.AppendLine("    <Import Include=\"System.Web.UI\" />");
            _str.AppendLine("    <Import Include=\"System.Web.UI.WebControls\" />");
            _str.AppendLine("    <Import Include=\"System.Web.UI.WebControls.WebParts\" />");
            _str.AppendLine("    <Import Include=\"System.Web.UI.HtmlControls\" />");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Content Include=\"Content\\Style.css\" />");
            _str.AppendLine("    <Content Include=\"Images\\game.png\" />");
            _str.AppendLine("    <Content Include=\"lib\\AjaxControlToolkit.dll\" />");
            _str.AppendLine("    <Content Include=\"lib\\AjaxMin.dll\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-grid.css\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-grid.min.css\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-reboot.css\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-reboot.min.css\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap.css\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap.min.css\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.bundle.js\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.bundle.min.js\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.js\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.min.js\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\popper.min.js\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\datta-icon.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\animate.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\bootstrap-datetimepicker.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\bootstrap.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\bootstrap.min.css\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\feather.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\font-awesome.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\font-awesome.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fontawesome-all.min.css\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\perfect-scrollbar.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fonts\\glyphicons-halflings-regular.svg\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\LICENSE.txt\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\main.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\main.esm.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\main.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\main.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\main.min.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\LICENSE.txt\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales-all.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales-all.min.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\af.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ar-dz.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ar-kw.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ar-ly.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ar-ma.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ar-sa.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ar-tn.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ar.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\bg.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\bs.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ca.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\cs.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\da.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\de.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\el.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\en-au.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\en-gb.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\en-nz.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\es-us.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\es.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\et.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\eu.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\fa.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\fi.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\fr-ca.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\fr-ch.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\fr.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\gl.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\he.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\hi.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\hr.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\hu.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\id.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\is.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\it.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ja.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ka.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\kk.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ko.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\lb.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\lt.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\lv.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\mk.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ms.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\nb.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\nl.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\nn.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\pl.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\pt-br.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\pt.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ro.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\ru.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\sk.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\sl.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\sq.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\sr-cyrl.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\sr.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\sv.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\th.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\tr.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\uk.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\vi.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\zh-cn.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\locales\\zh-tw.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\main.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\main.esm.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\main.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\main.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\main.min.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\LICENSE.txt\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\main.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\main.esm.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\main.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\main.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\main.min.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\interaction\\LICENSE.txt\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\interaction\\main.esm.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\interaction\\main.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\interaction\\main.min.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\LICENSE.txt\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\main.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\main.esm.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\main.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\main.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\main.min.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\LICENSE.txt\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\main.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\main.esm.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\main.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\main.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\main.min.js\" />");
            _str.AppendLine("    <Content Include=\"Content\\Site.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\toastr.min.css\" />");
            _str.AppendLine("    <Content Include=\"Content\\toastr.min.js\" />");
            _str.AppendLine("    <Content Include=\"Default.aspx\" />");
            _str.AppendLine("    <Content Include=\"favicon.ico\" />");
            _str.AppendLine("    <Content Include=\"fonts\\fontawesome-webfont.svg\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.svg\" />");
            _str.AppendLine("    <Content Include=\"Global.asax\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.woff2\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.woff\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.ttf\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.eot\" />");
            _str.AppendLine("    <Content Include=\"Images\\img_aberto.gif\" />");
            _str.AppendLine("    <Content Include=\"Images\\img_pago.gif\" />");
            _str.AppendLine("    <Content Include=\"Images\\logo.png\" />");
            _str.AppendLine("    <Content Include=\"Images\\minus.png\" />");
            _str.AppendLine("    <Content Include=\"Images\\plus.png\" />");
            _str.AppendLine("    <Content Include=\"LoginNovaSenha.aspx\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-grid.css.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-grid.min.css.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-reboot.css.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-reboot.min.css.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap.css.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap.min.css.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.bundle.js.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.bundle.min.js.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.js.map\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.min.js.map\" />");
            _str.AppendLine("    <Content Include=\"Images\\img_baixar.png\" />");
            _str.AppendLine("    <Content Include=\"Images\\img_nenhumItemCadastrado.gif\" />");
            _str.AppendLine("    <Content Include=\"Images\\img_semImagem.png\" />");
            _str.AppendLine("    <Content Include=\"Login.aspx\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\animate.min.css\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\bootstrap.min.css\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\bootstrap.min.js\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\fontawesome-all.min.css\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\pcoded.min.js\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\signin.css\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\Style.css\" />");
            _str.AppendLine("    <Content Include=\"ContentLogin\\vendor-all.min.js\" />");
            _str.AppendLine("    <Content Include=\"LoginRecuperarSenha.aspx\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-grid.css\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-grid.min.css\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-reboot.css\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap-reboot.min.css\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap.css\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\css\\bootstrap.min.css\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.bundle.js\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.bundle.min.js\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.js\" />");
            _str.AppendLine("    <Content Include=\"Pluguins\\Boostrap_4.3\\js\\bootstrap.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\bootstrap-datetimepicker.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\bootstrap.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\frmGeral.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\jquery-3.3.1.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\jquery.mask.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\MensagemJS.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\modernizr-2.8.3.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\moment-with-locales.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\moment.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\vendor-all.min.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\DetailsView.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\Focus.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\GridView.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\Menu.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MenuStandards.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjax.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxApplicationServices.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxComponentModel.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxCore.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxGlobalization.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxHistory.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxNetwork.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxSerialization.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxTimer.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxWebForms.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\MSAjax\\MicrosoftAjaxWebServices.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\SmartNav.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\TreeView.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\WebForms.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\WebParts.js\" />");
            _str.AppendLine("    <Content Include=\"Scripts\\WebForms\\WebUIValidation.js\" />");
            _str.AppendLine("    <Content Include=\"SqlServerTypes\\Loader.cs\" />");
            _str.AppendLine("    <Content Include=\"SqlServerTypes\\readme.htm\" />");
            _str.AppendLine("    <Content Include=\"SqlServerTypes\\x64\\msvcr120.dll\">");
            _str.AppendLine("      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>");
            _str.AppendLine("    </Content>");
            _str.AppendLine("    <Content Include=\"SqlServerTypes\\x64\\SqlServerSpatial140.dll\">");
            _str.AppendLine("      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>");
            _str.AppendLine("    </Content>");
            _str.AppendLine("    <Content Include=\"SqlServerTypes\\x86\\msvcr120.dll\">");
            _str.AppendLine("      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>");
            _str.AppendLine("    </Content>");
            _str.AppendLine("    <Content Include=\"SqlServerTypes\\x86\\SqlServerSpatial140.dll\">");
            _str.AppendLine("      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>");
            _str.AppendLine("    </Content>");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_CAD200_SMTP.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_CAD100_CONTEUDO.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_CAD300_DEPOIMENTO.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_CAD400_GAMES.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_LKP003_IDADE.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_PACIENTES.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_LKP002_CATEGORIA_CONTEUDO.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WF\\form_LKP001_TIPO_CANCER.aspx\" />");
            _str.AppendLine("    <Content Include=\"UI_WUC\\wuc_CAD401_IMAGEM_JOGO_MEMORIA.ascx\" />");
            _str.AppendLine("    <Content Include=\"UI_WUC\\wuc_CAD101_CONTEUDO_ITEM.ascx\" />");
            _str.AppendLine("    <Content Include=\"UI_WUC\\wuc_VER_CONTEUDO.ascx\" />");
            _str.AppendLine("    <Content Include=\"Web.config\" />");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Compile Include=\"api\\arguments\\ApplicationUser.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\arguments\\Categoria.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\arguments\\Conteudo.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\arguments\\Depoimento.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\arguments\\ResumoConteudo.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\arguments\\ResumoGame.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\config\\WebApiConfig.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\controller\\ValuesController1.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\controller\\ConteudoController.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\controller\\VisitanteCategoriaController.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\controller\\SobreController.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\controller\\DepoimentoController.vb\" />");
            _str.AppendLine("    <Compile Include=\"api\\controller\\VisitanteGameController.vb\" />");
            _str.AppendLine("    <Compile Include=\"App_Start\\BundleConfig.vb\" />");
            _str.AppendLine("    <Compile Include=\"App_Start\\RouteConfig.vb\" />");
            _str.AppendLine("    <Compile Include=\"BLL\\Agendamento.vb\" />");
            _str.AppendLine("    <Compile Include=\"BLL\\DadosSESSAO.vb\" />");
            _str.AppendLine("    <Compile Include=\"BLL\\Extensoes.vb\" />");
            _str.AppendLine("    <Compile Include=\"BLL\\MontadorConteudo.vb\" />");
            _str.AppendLine("    <Compile Include=\"BLL\\SESSAO.vb\" />");
            _str.AppendLine("    <Compile Include=\"DAL\\Conexao.vb\" />");
            _str.AppendLine("    <Compile Include=\"Default.aspx.vb\">");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("      <DependentUpon>Default.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"Default.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>Default.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"Global.asax.vb\">");
            _str.AppendLine("      <DependentUpon>Global.asax</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"Login.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>Login.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"Login.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>Login.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodebehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"api\\controller\\LoginController.vb\" />");
            _str.AppendLine("    <Compile Include=\"LoginNovaSenha.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>LoginNovaSenha.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"LoginNovaSenha.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>LoginNovaSenha.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodebehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"LoginRecuperarSenha.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>LoginRecuperarSenha.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"LoginRecuperarSenha.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>LoginRecuperarSenha.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodebehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"My Project\\AssemblyInfo.vb\" />");
            _str.AppendLine("    <Compile Include=\"My Project\\Application.Designer.vb\">");
            _str.AppendLine("      <AutoGen>True</AutoGen>");
            _str.AppendLine("      <DependentUpon>Application.myapp</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"My Project\\MyExtensions\\MyWebExtension.vb\">");
            _str.AppendLine("      <VBMyExtensionTemplateID>Microsoft.VisualBasic.Web.MyExtension</VBMyExtensionTemplateID>");
            _str.AppendLine("      <VBMyExtensionTemplateVersion>1.0.0.0</VBMyExtensionTemplateVersion>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"My Project\\Resources.Designer.vb\">");
            _str.AppendLine("      <AutoGen>True</AutoGen>");
            _str.AppendLine("      <DesignTime>True</DesignTime>");
            _str.AppendLine("      <DependentUpon>Resources.resx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"My Project\\Settings.Designer.vb\">");
            _str.AppendLine("      <AutoGen>True</AutoGen>");
            _str.AppendLine("      <DependentUpon>Settings.settings</DependentUpon>");
            _str.AppendLine("      <DesignTimeSharedInput>True</DesignTimeSharedInput>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"Site.Master.designer.vb\">");
            _str.AppendLine("      <DependentUpon>Site.Master</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"Site.Master.vb\">");
            _str.AppendLine("      <DependentUpon>Site.Master</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD200_SMTP.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD200_SMTP.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD200_SMTP.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD200_SMTP.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodebehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD100_CONTEUDO.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD100_CONTEUDO.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD100_CONTEUDO.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD100_CONTEUDO.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD300_DEPOIMENTO.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD300_DEPOIMENTO.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD300_DEPOIMENTO.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD300_DEPOIMENTO.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodebehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD400_GAMES.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD400_GAMES.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_CAD400_GAMES.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_CAD400_GAMES.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_LKP003_IDADE.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_LKP003_IDADE.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_LKP003_IDADE.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_LKP003_IDADE.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodebehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_PACIENTES.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_PACIENTES.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_PACIENTES.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_PACIENTES.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_LKP002_CATEGORIA_CONTEUDO.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_LKP002_CATEGORIA_CONTEUDO.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_LKP002_CATEGORIA_CONTEUDO.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_LKP002_CATEGORIA_CONTEUDO.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_LKP001_TIPO_CANCER.aspx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>form_LKP001_TIPO_CANCER.aspx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WF\\form_LKP001_TIPO_CANCER.aspx.vb\">");
            _str.AppendLine("      <DependentUpon>form_LKP001_TIPO_CANCER.aspx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodebehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WUC\\wuc_CAD401_IMAGEM_JOGO_MEMORIA.ascx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>wuc_CAD401_IMAGEM_JOGO_MEMORIA.ascx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WUC\\wuc_CAD401_IMAGEM_JOGO_MEMORIA.ascx.vb\">");
            _str.AppendLine("      <DependentUpon>wuc_CAD401_IMAGEM_JOGO_MEMORIA.ascx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WUC\\wuc_CAD101_CONTEUDO_ITEM.ascx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>wuc_CAD101_CONTEUDO_ITEM.ascx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WUC\\wuc_CAD101_CONTEUDO_ITEM.ascx.vb\">");
            _str.AppendLine("      <DependentUpon>wuc_CAD101_CONTEUDO_ITEM.ascx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WUC\\wuc_VER_CONTEUDO.ascx.designer.vb\">");
            _str.AppendLine("      <DependentUpon>wuc_VER_CONTEUDO.ascx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UI_WUC\\wuc_VER_CONTEUDO.ascx.vb\">");
            _str.AppendLine("      <DependentUpon>wuc_VER_CONTEUDO.ascx</DependentUpon>");
            _str.AppendLine("      <SubType>ASPXCodeBehind</SubType>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("    <Compile Include=\"UploadArquivo.ashx.vb\">");
            _str.AppendLine("      <DependentUpon>UploadArquivo.ashx</DependentUpon>");
            _str.AppendLine("    </Compile>");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <EmbeddedResource Include=\"My Project\\Resources.resx\">");
            _str.AppendLine("      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>");
            _str.AppendLine("      <LastGenOutput>Resources.Designer.vb</LastGenOutput>");
            _str.AppendLine("      <CustomToolNamespace>My.Resources</CustomToolNamespace>");
            _str.AppendLine("      <SubType>Designer</SubType>");
            _str.AppendLine("    </EmbeddedResource>");
            _str.AppendLine("    <Content Include=\"UI_RPT\\rpt_ANIVERSARIANTES_MES.rdlc\" />");
            _str.AppendLine("    <Content Include=\"UI_RPT\\rpt_LISTAGEM_PACIENTES.rdlc\" />");
            _str.AppendLine("    <Content Include=\"UI_RPT\\rpt_TABELA_PRECOS.rdlc\" />");
            _str.AppendLine("    <Content Include=\"UI_RPT\\rpt_ATENDIMENTOS.rdlc\" />");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Content Include=\"Content\\fonts\\glyphicons-halflings-regular.eot\" />");
            _str.AppendLine("    <Content Include=\"Content\\fonts\\glyphicons-halflings-regular.ttf\" />");
            _str.AppendLine("    <Content Include=\"Content\\fonts\\glyphicons-halflings-regular.woff\" />");
            _str.AppendLine("    <Content Include=\"Content\\fonts\\glyphicons-halflings-regular.woff2\" />");
            _str.AppendLine("    <Content Include=\"fonts\\FontAwesome.otf\" />");
            _str.AppendLine("    <Content Include=\"fonts\\fontawesome-webfont.eot\" />");
            _str.AppendLine("    <Content Include=\"fonts\\fontawesome-webfont.ttf\" />");
            _str.AppendLine("    <Content Include=\"fonts\\fontawesome-webfont.woff\" />");
            _str.AppendLine("    <Content Include=\"fonts\\fontawesome-webfont.woff2\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.eot\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.ttf\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.woff\" />");
            _str.AppendLine("    <Content Include=\"fonts\\glyphicons-halflings-regular.woff2\" />");
            _str.AppendLine("    <Content Include=\"fonts\\summernote.eot\" />");
            _str.AppendLine("    <Content Include=\"fonts\\summernote.ttf\" />");
            _str.AppendLine("    <Content Include=\"fonts\\summernote.woff\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\package.json\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\core\\README.md\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\package.json\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\daygrid\\README.md\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\package.json\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\list\\README.md\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\package.json\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\timegrid\\README.md\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\interaction\\package.json\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\interaction\\README.md\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-grid.css.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-grid.min.css.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-reboot.css.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap-reboot.min.css.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap.css.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\css\\bootstrap.min.css.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.bundle.js.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.bundle.min.js.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.js.map\" />");
            _str.AppendLine("    <Content Include=\"Boostrap\\js\\bootstrap.min.js.map\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\package.json\" />");
            _str.AppendLine("    <Content Include=\"Content\\fullcalendar\\bootstrap\\README.md\" />");
            _str.AppendLine("    <None Include=\"My Project\\Application.myapp\">");
            _str.AppendLine("      <Generator>MyApplicationCodeGenerator</Generator>");
            _str.AppendLine("      <LastGenOutput>Application.Designer.vb</LastGenOutput>");
            _str.AppendLine("    </None>");
            _str.AppendLine("    <None Include=\"My Project\\Settings.settings\">");
            _str.AppendLine("      <Generator>SettingsSingleFileGenerator</Generator>");
            _str.AppendLine("      <CustomToolNamespace>My</CustomToolNamespace>");
            _str.AppendLine("      <LastGenOutput>Settings.Designer.vb</LastGenOutput>");
            _str.AppendLine("    </None>");
            _str.AppendLine("    <Content Include=\"Site.Master\" />");
            _str.AppendLine("    <None Include=\"packages.config\" />");
            _str.AppendLine("    <Content Include=\"UploadArquivo.ashx\" />");
            _str.AppendLine("    <None Include=\"Web.Debug.config\">");
            _str.AppendLine("      <DependentUpon>Web.config</DependentUpon>");
            _str.AppendLine("    </None>");
            _str.AppendLine("    <None Include=\"Web.Release.config\">");
            _str.AppendLine("      <DependentUpon>Web.config</DependentUpon>");
            _str.AppendLine("    </None>");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Folder Include=\"App_Data\\\" />");
            _str.AppendLine("    <Folder Include=\"bin\\\" />");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <ProjectReference Include=\"..\\smile.DAL\\smile.DAL.vbproj\">");
            _str.AppendLine("      <Project>{c77f68b7-9f13-4641-9b25-3fe268eadacf}</Project>");
            _str.AppendLine("      <Name>smile.DAL</Name>");
            _str.AppendLine("    </ProjectReference>");
            _str.AppendLine("    <ProjectReference Include=\"..\\smile.Geral\\smile.Geral.vbproj\">");
            _str.AppendLine("      <Project>{16629943-5341-40BC-9F55-6300E8582BFA}</Project>");
            _str.AppendLine("      <Name>smile.Geral</Name>");
            _str.AppendLine("    </ProjectReference>");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <TypeScriptCompile Include=\"Content\\fullcalendar\\bootstrap\\main.d.ts\" />");
            _str.AppendLine("    <TypeScriptCompile Include=\"Content\\fullcalendar\\core\\main.d.ts\" />");
            _str.AppendLine("    <TypeScriptCompile Include=\"Content\\fullcalendar\\daygrid\\main.d.ts\" />");
            _str.AppendLine("    <TypeScriptCompile Include=\"Content\\fullcalendar\\interaction\\main.d.ts\" />");
            _str.AppendLine("    <TypeScriptCompile Include=\"Content\\fullcalendar\\list\\main.d.ts\" />");
            _str.AppendLine("    <TypeScriptCompile Include=\"Content\\fullcalendar\\timegrid\\main.d.ts\" />");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <ItemGroup>");
            _str.AppendLine("    <Service Include=\"{4A0DDDB5-7A95-4FBF-97CC-616D07737A77}\" />");
            _str.AppendLine("  </ItemGroup>");
            _str.AppendLine("  <PropertyGroup>");
            _str.AppendLine("    <VisualStudioVersion Condition=\"'$(VisualStudioVersion)' == ''\">10.0</VisualStudioVersion>");
            _str.AppendLine("    <VSToolsPath Condition=\"'$(VSToolsPath)' == ''\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)</VSToolsPath>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <PropertyGroup>");
            _str.AppendLine("    <OptionExplicit>On</OptionExplicit>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <PropertyGroup>");
            _str.AppendLine("    <OptionCompare>Binary</OptionCompare>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <PropertyGroup>");
            _str.AppendLine("    <OptionStrict>Off</OptionStrict>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <PropertyGroup>");
            _str.AppendLine("    <OptionInfer>On</OptionInfer>");
            _str.AppendLine("  </PropertyGroup>");
            _str.AppendLine("  <Import Project=\"$(MSBuildBinPath)\\Microsoft.VisualBasic.targets\" />");
            _str.AppendLine("  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.targets\" Condition=\"Exists('$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\TypeScript\\Microsoft.TypeScript.targets')\" />");
            _str.AppendLine("  <Import Project=\"$(VSToolsPath)\\WebApplications\\Microsoft.WebApplication.targets\" Condition=\"'$(VSToolsPath)' != ''\" />");
            _str.AppendLine("  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v10.0\\WebApplications\\Microsoft.WebApplication.targets\" Condition=\"false\" />");
            _str.AppendLine("  <ProjectExtensions>");
            _str.AppendLine("    <VisualStudio>");
            _str.AppendLine("      <FlavorProperties GUID=\"{349c5851-65df-11da-9384-00065b846f21}\">");
            _str.AppendLine("        <WebProjectProperties>");
            _str.AppendLine("          <UseIIS>True</UseIIS>");
            _str.AppendLine("          <AutoAssignPort>True</AutoAssignPort>");
            _str.AppendLine("          <DevelopmentServerPort>63403</DevelopmentServerPort>");
            _str.AppendLine("          <DevelopmentServerVPath>/</DevelopmentServerVPath>");
            _str.AppendLine("          <IISUrl>http://localhost:63440/</IISUrl>");
            _str.AppendLine("          <NTLMAuthentication>False</NTLMAuthentication>");
            _str.AppendLine("          <UseCustomServer>False</UseCustomServer>");
            _str.AppendLine("          <CustomServerUrl>");
            _str.AppendLine("          </CustomServerUrl>");
            _str.AppendLine("          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>");
            _str.AppendLine("        </WebProjectProperties>");
            _str.AppendLine("      </FlavorProperties>");
            _str.AppendLine("    </VisualStudio>");
            _str.AppendLine("  </ProjectExtensions>");
            _str.AppendLine("  <Target Name=\"EnsureNuGetPackageBuildImports\" BeforeTargets=\"PrepareForBuild\">");
            _str.AppendLine("    <PropertyGroup>");
            _str.AppendLine("      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>");
            _str.AppendLine("    </PropertyGroup>");
            _str.AppendLine("    <Error Condition=\"!Exists('..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\packages\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\\build\\net46\\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props'))\" />");
            _str.AppendLine("  </Target>");
            _str.AppendLine("  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. ");
            _str.AppendLine("       Other similar extension points exist, see Microsoft.Common.targets.");
            _str.AppendLine("  <Target Name=\"BeforeBuild\">");
            _str.AppendLine("  </Target>");
            _str.AppendLine("  <Target Name=\"AfterBuild\">");
            _str.AppendLine("  </Target>");
            _str.AppendLine("  -->");
            _str.AppendLine("</Project>");

            return _str.ToString();
        }

    }
}